// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zgvesuvoeqhvbonreemh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpndmVzdXZvZXFodmJvbnJlZW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzM1MDYsImV4cCI6MjA3MzM0OTUwNn0.Mzh4iYUVR1Y4RUiZAkEprN4cv9acDeUH2Y8eqOnCLhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);